namespace ConsoleApp1;

public static class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine("Euler 2 problem");
        const int border = 4000000;
        Console.WriteLine("Sum of the even-valued terms of Fibonacci sequence using recursion: " +
                          $"{FibUtils.SumOfEvenFibonacciTermsRec(border)}");
        Console.WriteLine("Sum of the even-valued terms of Fibonacci sequence using tail recursion: " +
                          $"{FibUtils.SumOfEvenFibonacciTermsTail(border)}");
        
        
        Console.WriteLine("Euler 29 problem");
        const int min = 2;
        const int max = 100;
        var lst = new List<double>();
        for (var a = min; a <= max; a++)
        {
            for (var b = min; b <= max; b++)
            {
                lst.Add(Math.Pow(a, b));
            }
        }
        var distinctResult = lst.Distinct().ToList();
        distinctResult.Sort();
        Console.WriteLine($"Amount of distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?: {distinctResult.Count}");
        Console.ReadLine();
    }
}