name: F# workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: lab1.sln
      # Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

  format:
    runs-on: windows-latest
    steps:
    - name: Format code
      run: dotnet fantomas --check ./Fsharp
  lint:
    runs-on: windows-latest
    steps:
    - name: Lint code
      run: dotnet fsharplint lint ./Fsharp

    # # Execute all unit tests in the solution
    # - name: Execute unit tests
    #   run: dotnet test
